backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Cover"
      name: "home"
      file: "content/cover.md"
      fields:
        - { label: "Name", name: "name", widget: "string"}
        - { label: "Position", name: "position", widget: "string"}
        - { label: "Department", name: "department", widget: "string"}
        - { label: "Specialization", name: "specialization", widget: "string"}
        - { label: "Experience", name: "experience", widget: "string"}
        - { label: "Status", name: "status", widget: "string"}