backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Cover"
      name: "home"
      file: "content/cover.md"
      fields:
        - { label: "Name", name: "name", widget: "string"}
        - { label: "Position", name: "position", widget: "string"}
        - { label: "Department", name: "department", widget: "string"}
        - { label: "Specialization", name: "specialization", widget: "string"}
        - { label: "Experience", name: "experience", widget: "string"}
        - { label: "Status", name: "status", widget: "string"}
    - label: "About"
      name: "about"
      file: "content/about.md"
      fields:
        - { label: "Introduction", name: "intro", widget: "markdown"}
        - label: "Jobs"
          name: "jobs"
          widget: list
          fields:
            - { label: "Company Name", name: "company_name", widget: "string", required: true}
            - { label: "Role", name: "role", widget: "string", required: true}
            - label: "Start Year"
              name: "start_year"
              widget: "number"
              value_type: "int"
              min: 2018
              max: 2050
              required: true
            - label: "End Year"
              name: "end_year"
              widget: "number"
              value_type: "int"
              min: 2018
              max: 2050
            - label: "Job Details"
              name: "job_details"
              widget: "list"
              fields:
                - { label: "Detail", name: "detail", widget: "string"}
    - label: "Skills"
      name: "skills"
      file: "content/skills.md"
      fields:
        - label: "Skills Box"
          name: "skills_box"
          widget: "list"
          fields:
            - {label: "Title", name: "title", widget: "string"}
            - label: "Skill List"
              name: "skill_list"
              widget: "list"
              fields:
                - {label: "Skill Name", name: "skill_name", widget: "string"}